// ============================================================================
// SHARED UTILITIES — DO NOT EDIT THIS FILE
// ============================================================================

function setText(id, val) {
  const el = document.getElementById(id);
  if (el) el.textContent = val;
}

function setHTML(id, val) {
  const el = document.getElementById(id);
  if (el) el.innerHTML = val;
}

// Injects elements common to every page (nav logo, contact, footer)
function initCommon() {
  setText('logo', SITE.brandShort);

  setHTML('contactHeading', `${SITE.contactHeading} <em>${SITE.contactHeadingItalic}</em>`);
  const wa = document.getElementById('whatsappLink');
  if (wa) { wa.href = SITE.whatsappLink; wa.textContent = SITE.whatsappNumber; }
  const ig = document.getElementById('instagramLink');
  if (ig) { ig.href = SITE.instagramLink; ig.textContent = SITE.instagramHandle; }
  setText('locationText', SITE.locationText);

  setText('footerLeft', SITE.footerLeft);
  setText('footerRight', SITE.footerRight);

  // Highlight current page in nav
  const page = document.body.dataset.page;
  document.querySelectorAll('.nav-links a[data-nav]').forEach(function(a) {
    if (a.dataset.nav === page) a.classList.add('active');
  });
}

// Wires up the IntersectionObserver for scroll-reveal
function initReveal() {
  const observer = new IntersectionObserver(function(entries) {
    entries.forEach(function(e) {
      if (e.isIntersecting) e.target.classList.add('visible');
    });
  }, { threshold: 0.1 });
  document.querySelectorAll('.reveal-up, .reveal-left, .reveal-right').forEach(function(el) {
    observer.observe(el);
  });
}
