// ============================================================================
// SITE.JS — DO NOT EDIT THIS FILE
// All text content lives in data.js — that is the only file you need to touch.
// ============================================================================


// --- Helpers -----------------------------------------------------------------

function setText(id, val) {
  var el = document.getElementById(id);
  if (el) el.textContent = val || '';
}

function setHTML(id, val) {
  var el = document.getElementById(id);
  if (el) el.innerHTML = val || '';
}


// --- Common (runs on every page) ---------------------------------------------

function initCommon() {
  setText('logo', SITE.brandShort);

  // Contact heading
  setHTML('contactHeading', SITE.contactHeading + ' <em>' + SITE.contactHeadingItalic + '</em>');

  // Build contact methods from data.js — add/remove fields there, not here
  var contactEl = document.getElementById('contactMethods');
  if (contactEl) {
    var methods = [];
    if (SITE.whatsappNumber)  methods.push({ label: 'WhatsApp',  href: SITE.whatsappLink,   text: SITE.whatsappNumber });
    if (SITE.email)           methods.push({ label: 'Email',     href: SITE.emailLink,      text: SITE.email });
    if (SITE.instagramHandle) methods.push({ label: 'Instagram', href: SITE.instagramLink,  text: SITE.instagramHandle, target: '_blank' });
    if (SITE.locationText)    methods.push({ label: 'Location',  text: SITE.locationText });

    contactEl.innerHTML = methods.map(function(m, i) {
      var inner = m.href
        ? '<a href="' + m.href + '"' + (m.target ? ' target="' + m.target + '"' : '') + '>' + m.text + '</a>'
        : '<span>' + m.text + '</span>';
      return '<div class="contact-method reveal-up delay-' + (i + 2) + '">'
        + '<div class="label">' + m.label + '</div>' + inner + '</div>';
    }).join('');
  }

  // Footer
  setText('footerLeft',  SITE.footerLeft);
  setText('footerRight', SITE.footerRight);

  // Highlight current page link in nav
  var page = document.body.getAttribute('data-page');
  document.querySelectorAll('.nav-links a[data-nav]').forEach(function(a) {
    if (a.getAttribute('data-nav') === page) a.classList.add('active');
  });
}


// --- Scroll-reveal -----------------------------------------------------------

function initReveal() {
  var observer = new IntersectionObserver(function(entries) {
    entries.forEach(function(e) {
      if (e.isIntersecting) e.target.classList.add('visible');
    });
  }, { threshold: 0.1 });
  document.querySelectorAll('.reveal-up, .reveal-left, .reveal-right').forEach(function(el) {
    observer.observe(el);
  });
}


// --- Home page ---------------------------------------------------------------

function initHomePage() {
  setText('metaLeft',  SITE.metaLeft);
  setText('metaRight', SITE.metaRight);

  // Marquee
  var name  = SITE.brandFull.replace('/', '<span class="slash">/</span>');
  var track = document.getElementById('marqueeTrack');
  if (track) {
    var repeated = '';
    for (var r = 0; r < 4; r++) repeated += '<span>' + name + '</span>';
    track.innerHTML = repeated;
  }

  // Hero
  setText('tagline',      SITE.tagline);
  setText('ctaPrimary',   SITE.ctaPrimary);
  setText('ctaSecondary', SITE.ctaSecondary);

  // Philosophy
  setHTML('philosophyHeading', SITE.philosophyHeading + ' <em>' + SITE.philosophyHeadingItalic + '</em>');
  setText('philosophyParagraph1', SITE.philosophyParagraph1);
  setText('philosophyParagraph2', SITE.philosophyParagraph2);
  setText('philosophyParagraph3', SITE.philosophyParagraph3);

  // Featured client quote — hidden automatically if featuredQuote is "" in data.js
  var ftSection = document.getElementById('featuredTestimonial');
  if (ftSection) {
    if (SITE.featuredQuote) {
      setHTML('featuredQuoteText', '“' + SITE.featuredQuote + '”');
      setText('featuredCiteText', '— ' + SITE.featuredCite);
    } else {
      ftSection.style.display = 'none';
    }
  }
}


// --- About page --------------------------------------------------------------

function initAboutPage() {
  // Personal intro — hidden if aboutIntro is "" in data.js
  var introSection = document.getElementById('aboutIntroSection');
  if (introSection) {
    if (SITE.aboutIntro) {
      setText('aboutIntroText', SITE.aboutIntro);
    } else {
      introSection.style.display = 'none';
    }
  }

  // Hobbies — hidden if hobbies is "" in data.js
  var hobbiesSection = document.getElementById('hobbiesSection');
  if (hobbiesSection) {
    if (SITE.hobbies) {
      setText('hobbiesText', SITE.hobbies);
    } else {
      hobbiesSection.style.display = 'none';
    }
  }

  // Articles — hidden if no articles are filled in data.js
  var articlesSection = document.getElementById('articlesSection');
  if (articlesSection) {
    var hasAny = SITE.article1Title || SITE.article2Title || SITE.article3Title;
    if (!hasAny) {
      articlesSection.style.display = 'none';
    } else {
      setHTML('articlesHeading', SITE.articlesHeading + ' <em>' + SITE.articlesHeadingItalic + '</em>');

      // Featured articles 1-3: alternating image/text layout
      var featuredEl = document.getElementById('articlesFeatured');
      if (featuredEl) {
        var html = '';
        for (var f = 1; f <= 3; f++) {
          var t = SITE['article' + f + 'Title'];
          var e = SITE['article' + f + 'Excerpt'];
          var l = SITE['article' + f + 'Link'];
          if (!t) continue;
          html += '<div class="article-featured reveal-up">'
            + '<div class="article-featured-image"><div class="image-placeholder">ARTICLE IMAGE ' + f + '</div></div>'
            + '<div class="article-featured-text">'
            + '<h3>' + t + '</h3>'
            + (e ? '<p>' + e + '</p>' : '')
            + (l ? '<a class="article-read-link" href="' + l + '" target="_blank">Read on Substack <span>→</span></a>' : '')
            + '</div>'
            + '</div>';
        }
        featuredEl.innerHTML = html;
      }

      // Archive articles 4-6: compact scrollable list
      var archiveWrapper = document.getElementById('articlesArchiveWrapper');
      if (archiveWrapper) {
        var archiveHTML = '';
        for (var a = 4; a <= 6; a++) {
          var at = SITE['article' + a + 'Title'];
          var ae = SITE['article' + a + 'Excerpt'];
          var al = SITE['article' + a + 'Link'];
          if (!at) continue;
          var tag = al ? 'a' : 'div';
          var attrs = al ? ' href="' + al + '" target="_blank"' : '';
          archiveHTML += '<' + tag + ' class="article-archive-item"' + attrs + '>'
            + '<span class="article-archive-title">' + at + '</span>'
            + (ae ? '<span class="article-archive-excerpt">' + ae + '</span>' : '')
            + '<span class="article-archive-arrow">→</span>'
            + '</' + tag + '>';
        }
        if (archiveHTML) {
          document.getElementById('articlesArchive').innerHTML = archiveHTML;
        } else {
          archiveWrapper.style.display = 'none';
        }
      }

      // Substack link
      var substackEl = document.getElementById('articlesSubstack');
      if (substackEl) {
        if (SITE.substackLink) {
          substackEl.innerHTML = '<a href="' + SITE.substackLink + '" target="_blank">Read all on Substack →</a>';
        } else {
          substackEl.style.display = 'none';
        }
      }
    }
  }

  // Process section
  setHTML('processHeading', SITE.processHeading + ' <em>' + SITE.processHeadingItalic + '</em>');
  setText('processIntro', SITE.processIntro);

  for (var i = 1; i <= 4; i++) {
    setText('process' + i + 'Number', SITE['process' + i + 'Number']);
    setText('process' + i + 'Title',  SITE['process' + i + 'Title']);

    // Bold the first sentence for scannability
    var body = SITE['process' + i + 'Body'];
    var el   = document.getElementById('process' + i + 'Body');
    if (el) {
      var dot = body.indexOf('. ');
      el.innerHTML = dot > 0
        ? '<strong>' + body.slice(0, dot + 1) + '</strong> ' + body.slice(dot + 2)
        : body;
    }
  }
}


// --- Book Now page -----------------------------------------------------------

function initBookPage() {
  // Services overview — hidden if servicesOverview is "" in data.js
  var overviewSection = document.getElementById('servicesOverviewSection');
  var overviewEl      = document.getElementById('servicesOverviewText');
  if (overviewSection && overviewEl) {
    if (SITE.servicesOverview) {
      overviewEl.textContent = SITE.servicesOverview;
    } else {
      overviewSection.style.display = 'none';
    }
  }

  setHTML('servicesHeading', SITE.servicesHeading + ' <em>' + SITE.servicesHeadingItalic + '</em>');

  var bookLabels = [
    'Book Trial Session',
    'Book 4-Session Pack',
    'Book 8-Session Pack',
    'Start Online Coaching'
  ];

  for (var i = 1; i <= 4; i++) {
    setText('service' + i + 'Title', SITE['service' + i + 'Title']);
    setText('service' + i + 'Price', SITE['service' + i + 'Price']);
    setText('service' + i + 'Desc',  SITE['service' + i + 'Desc']);

    // Pack detail renders as bullet list — items separated by " / " in data.js
    var detail   = SITE['service' + i + 'Detail'];
    var detailEl = document.getElementById('service' + i + 'Detail');
    if (detailEl) {
      if (detail) {
        detailEl.innerHTML = '<ul class="pack-detail-list">'
          + detail.split(' / ').map(function(item) { return '<li>' + item + '</li>'; }).join('')
          + '</ul>';
      } else {
        detailEl.style.display = 'none';
      }
    }

    // Booking button — opens WhatsApp with the package name pre-filled
    var bookEl = document.getElementById('service' + i + 'Book');
    if (bookEl) {
      var msg = encodeURIComponent("Hi Brandon, I'd like to enquire about the " + SITE['service' + i + 'Title'] + '.');
      bookEl.innerHTML = '<a class="btn-book" href="' + SITE.whatsappLink + '?text=' + msg + '" target="_blank">'
        + bookLabels[i - 1] + '</a>';
    }
  }
}


// --- Testimonials page -------------------------------------------------------

function initTestimonialsPage() {
  setHTML('testimonialsHeading', SITE.testimonialsHeading + ' <em>' + SITE.testimonialsHeadingItalic + '</em>');

  for (var i = 1; i <= 4; i++) {
    setText('testimonial' + i + 'Quote', SITE['testimonial' + i + 'Quote']);
    setText('testimonial' + i + 'Cite',  SITE['testimonial' + i + 'Cite']);
  }

  setHTML('credsHeading', SITE.credsHeading + ' <em>' + SITE.credsHeadingItalic + '</em>');
  for (var j = 1; j <= 3; j++) {
    setText('cred' + j + 'Name',   SITE['cred' + j + 'Name']);
    setText('cred' + j + 'Status', SITE['cred' + j + 'Status']);
  }
}
